AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create AlertLogic IDS security infrastructure inside a VPC. The artifacts
  created are: Security Group, Launch Template for IDS security appliances that
  uses the Security Group and an Autoscaling Group that uses the Launch Template.'
Parameters:
  AccountId:
    Description: Enter your AlertLogic account ID.
    Type: String
    AllowedPattern: "^[1-9][0-9]*$"
    ConstraintDescription: must be a valid AlertLogic account ID
  VpcId:
    Description: Select a target VPC to deploy security infrastructure.
    Type: AWS::EC2::VPC::Id
    ConstraintDescription: must be a valid VPC ID
  VpcCidr:
    Description: 'This CIDR range allows agents to connect to the IDS appliances.   By default, it should match the CIDR
       of the protected VPC above, but may need to be adjusted if VPC peering is in use.'
    Type: String
    AllowedPattern: "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}/[0-9]{1,2}$"
    ConstraintDescription: must be a valid CIDR
  SubnetId:
    Description: 'Select the target subnets.  The autoscaling group will be able to launch appliances in each subnet listed.
        Adding a subnet from each availablity zone in use will enable the IDS appliance to be scaled across AZs if needed.
        Note - Subnets selected must all be either Public or Private.   They cannot be mixed.'
    Type: List<AWS::EC2::Subnet::Id>
    ConstraintDescription: must be a valid existing subnet ID list
  AssignPublicIp:
    Type: String
    Description: If the selected subnets are Public (internet gateway), set this to true.   Otherwise select false.
    Default: 'true'
    AllowedValues:
    - 'true'
    - 'false'
  InstanceType:
    Description: Select the instance type for the IDS security appliance(s)
    Type: String
    Default: c5.large
    AllowedValues:
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - c4.large
    - c4.xlarge
    - c4.2xlarge
    - c5.large
    - c5.xlarge
    - c5.2xlarge
    ConstraintDescription: must be a valid EC2 instance type
  NumAppliances:
    Description: Enter a desired number of security appliances
    Type: Number
    Default: '1'
    MaxValue: '10'
    ConstraintDescription: must be an integer between 1 and 10
Conditions:
  AssignPublicIp:
    Fn::Equals:
    - 'true'
    - Ref: AssignPublicIp
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Alert Logic configuration
      Parameters:
      - AccountId
    - Label:
        default: Network Configuration
      Parameters:
      - VpcId
      - VpcCidr
      - SubnetId
      - AssignPublicIp
    - Label:
        default: IDS Security Appliances configuration
      Parameters:
      - InstanceType
      - NumAppliances
    ParameterLabels:
      AccountId:
        default: Alert Logic Account ID
      VpcId:
        default: Target VPC
      SubnetId:
        default: Target Subnet ID
      InstanceType:
        default: AWS instance type
      NumAppliances:
        default: Number of instances to deploy
      AssignPublicIp:
        default: Assign Public IP
Mappings:
  Internal:
    Tags:
      Version: v1.0.16m
  'Fn::Transform':
    Name: 'AWS::Include'
    Parameters:
      Location: s3://al-ms-cft-testing/ids_ami.json
Resources:
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub 'AlertLogic-IDS-ASG-${AccountId}-${VpcId}-${AWS::StackName}'
      VPCZoneIdentifier: !Ref SubnetId
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: !Ref NumAppliances
      MaxSize: !Ref NumAppliances
      DesiredCapacity: !Ref NumAppliances
      Tags:
      - Key: Name
        Value: AlertLogic IDS Security Appliance
        PropagateAtLaunch: 'true'
      - Key: AlertLogic-AccountID
        Value: !Ref AccountId
        PropagateAtLaunch: 'true'
      - Key: AlertLogic
        Value: Security
        PropagateAtLaunch: 'true'
      - Key: AlertLogic IDS Manual Mode Template Version
        Value: !FindInMap [ Internal, Tags, Version ]
        PropagateAtLaunch: 'true'
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub 'AlertLogic-IDS-Template-${AccountId}-${VpcId}-${AWS::StackName}'
      LaunchTemplateData:
        ImageId: !FindInMap [ RegionSettings, !Ref AWS::Region, ImageId ]
        InstanceType: !Ref InstanceType
        NetworkInterfaces:
          - DeviceIndex: 0
            DeleteOnTermination: true
            AssociatePublicIpAddress: !If [AssignPublicIp, 'true', 'false']
            Groups: [ !Ref SecurityGroup ]
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VpcId
      GroupName: !Sub 'AlertLogic IDS Security Group ${AccountId}/${VpcId}/${AWS::StackName}'
      GroupDescription: AlertLogic IDS Security Group
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp:
          Ref: VpcCidr
      - IpProtocol: tcp
        FromPort: '7777'
        ToPort: '7777'
        CidrIp:
          Ref: VpcCidr
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: '53'
        ToPort: '53'
        CidrIp: 8.8.4.4/32
      - IpProtocol: tcp
        FromPort: '53'
        ToPort: '53'
        CidrIp: 8.8.8.8/32
      - IpProtocol: udp
        FromPort: '53'
        ToPort: '53'
        CidrIp: 8.8.4.4/32
      - IpProtocol: udp
        FromPort: '53'
        ToPort: '53'
        CidrIp: 8.8.8.8/32
      - IpProtocol: tcp
        FromPort: '53'
        ToPort: '53'
        CidrIp: !Ref VpcCidr
      - IpProtocol: udp
        FromPort: '53'
        ToPort: '53'
        CidrIp: !Ref VpcCidr
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp: 185.54.124.0/24
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp: 204.110.218.96/27
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp: 204.110.219.96/27
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp: 208.71.209.32/27
      - IpProtocol: tcp
        FromPort: '4138'
        ToPort: '4138'
        CidrIp: 185.54.124.0/24
      - IpProtocol: tcp
        FromPort: '4138'
        ToPort: '4138'
        CidrIp: 204.110.218.96/27
      - IpProtocol: tcp
        FromPort: '4138'
        ToPort: '4138'
        CidrIp: 204.110.219.96/27
      - IpProtocol: tcp
        FromPort: '4138'
        ToPort: '4138'
        CidrIp: 208.71.209.32/27
      Tags:
      - Key: Name
        Value: !Sub 'AlertLogic IDS Security Group ${AccountId}/${VpcId}'
      - Key: AlertLogic-AccountID
        Value: !Ref AccountId
      - Key: AlertLogic
        Value: Security
      - Key: AlertLogic IDS Manual Mode Template Version
        Value: !FindInMap [ Internal, Tags, Version ]
Outputs:
  AccountId:
    Description: AlertLogic account ID
    Value: !Ref AccountId
  VpcId:
    Description: ID of the protected VPC
    Value: !Ref VpcId
  NumAppliances:
    Description: The number of created IDS security appliances
    Value: !Ref NumAppliances
  SecurityGroupId:
    Description: ID of the security group assigned to the IDS security appliances
    Value: !GetAtt SecurityGroup.GroupId
